// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcpQ0GNh3amlSRQ7uHCsyseB-HQBtlg1Y',
    appId: '1:564179883742:web:aa105dab209f9e151bd44f',
    messagingSenderId: '564179883742',
    projectId: 'pawhub-678c4',
    authDomain: 'pawhub-678c4.firebaseapp.com',
    storageBucket: 'pawhub-678c4.firebasestorage.app',
    measurementId: 'G-YTRMZ08XLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_9M5PPQSv9t9Q8qCEvWOA1Qaf02nTeqA',
    appId: '1:564179883742:android:a481c353bf5f831a1bd44f',
    messagingSenderId: '564179883742',
    projectId: 'pawhub-678c4',
    storageBucket: 'pawhub-678c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCxmxDZioRN_UsovZElXuVngreH2FIzyc',
    appId: '1:564179883742:ios:a5d2ecfd76c9103d1bd44f',
    messagingSenderId: '564179883742',
    projectId: 'pawhub-678c4',
    storageBucket: 'pawhub-678c4.firebasestorage.app',
    iosBundleId: 'com.example.pawhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCxmxDZioRN_UsovZElXuVngreH2FIzyc',
    appId: '1:564179883742:ios:a5d2ecfd76c9103d1bd44f',
    messagingSenderId: '564179883742',
    projectId: 'pawhub-678c4',
    storageBucket: 'pawhub-678c4.firebasestorage.app',
    iosBundleId: 'com.example.pawhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcpQ0GNh3amlSRQ7uHCsyseB-HQBtlg1Y',
    appId: '1:564179883742:web:251cb1f5c453a7361bd44f',
    messagingSenderId: '564179883742',
    projectId: 'pawhub-678c4',
    authDomain: 'pawhub-678c4.firebaseapp.com',
    storageBucket: 'pawhub-678c4.firebasestorage.app',
    measurementId: 'G-DXD7GXJM5S',
  );
}
